package rules

import cn.com.chengzi.drools.domain.model.Customer

rule "买了一瓶汽水"
salience 1
    when
        $c:Customer(money>0,$m:money, $e:emptyBottle, $d :drinkBottleSum);
    then
        $c.setMoney($m - 1);
        $c.setEmptyBottle($e + 1);
        $c.setDrinkBottleSum($d + 1);
        System.err.println($c.getName()+"有 " + $c.getMoney() + " 元， 有空瓶 " + $c.getEmptyBottle() + " 个， 喝了 " + $c.getDrinkBottleSum() + " 瓶。");
        update($c);
end

rule "用两个空瓶换了一瓶汽水"
salience 2
    when
        $c:Customer(emptyBottle > 1, $e:emptyBottle, $d:drinkBottleSum);
    then
        $c.setEmptyBottle($e - 2 + 1);
        $c.setDrinkBottleSum($d + 1);
         System.err.println($c.getName() + "有 "+$c.getMoney() + " 元， 有空瓶 " + $c.getEmptyBottle() + " 个(兑换了2个，又得到一个)， 喝了 " + $c.getDrinkBottleSum() + " 瓶。");
        update($c);
end

rule "结束"
//no-loop true
    when
         $c:Customer(money <= 0, emptyBottle < 2);
    then
         System.err.println("计算结束：" + $c.getName()+"有 " + $c.getMoney() + " 元， 有空瓶 " + $c.getEmptyBottle() + " 个， 喝了 " + $c.getDrinkBottleSum() + " 瓶。");
end